- modules/distribution/pom.xml
- modules/features/product/pom.xml
- modules/features/service/org.wso2.stratos.mb.dashboard.ui.feature/pom.xml
- modules/features/service/org.wso2.stratos.mb.deployment.feature/pom.xml
- modules/features/service/org.wso2.stratos.mb.login.ui.feature/pom.xml
- modules/integration/pom.xml
- modules/integration/tests-common/admin-clients/pom.xml
- modules/org.wso2.stratos.mb.login.ui/pom.xml
- modules/styles/product/pom.xml
- pom.xml
Removed versions from child poms and fixed andes stub dependency.
> Removed versions from child poms and fixed andes stub dependency.

- INSTALL.txt
- modules/distribution/src/main/assembly/filter.properties
- modules/samples/product/mqtt_IoTSample/pom.xml
- modules/samples/product/mqtt_chat_client/pom.xml
- modules/samples/product/simple_mqtt_client/pom.xml
- modules/styles/service/src/main/resources/web/product/about.html
- pom.xml
Removed SNAPSHOT references. Moved eclipse paho mqtt-client version to a property. Modified versions in samples.
> Removed SNAPSHOT references. Moved eclipse paho mqtt-client version to a property. Modified versions in samples.

- modules/samples/product/mqtt_IoTSample/pom.xml
- modules/samples/product/mqtt_chat_client/pom.xml
- pom.xml
Corrected paho repository URL. 
Removed repository references in samples.
> Corrected paho repository URL. Removed repository references in samples.

- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/backend/MBIntegrationBaseTest.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DurableTopicSubscriptionWithSameClientIdTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/artifacts/mb/config/allowSharedTopicSubscriptionsConfig/broker.xml
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
Test case added for 'ability to subscribe to a durable topic using same client id feature'.
Jira : https://wso2.org/jira/browse/MB-935
Redmine : https://redmine.wso2.com/issues/3427
> Add test cases for ability to subscribe to a durable topic using same client id feature

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/topic/TopicMessageReceiver.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DifferentSubscriptionsWithDurableTopicTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DurableTopicTestCase.java
DurableTopicTestCase and DurableMultipleTopicSubscriberTestCase are fixed.
> Test case durable fixing

- modules/integration/tests-integration/tests-amqp/src/test/resources/artifacts/mb/config/broker.xml
$subject. eliminates a config read error I saw in jenkins log.
> Minor changes to broker xml used in integration tests.

- modules/distribution/src/main/resources/log4j.properties
Some log appenders has become invalid after refactoring.
> Log4j Improvements

- modules/samples/product/jms_queue_client/src/org/sample/jms/Main.java
Fixed jms_queue_client sample. Invalid class name was used.
> Fixed jms_queue_client sample

- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
Issue is tracked with Jira https://wso2.org/jira/browse/MB-946
> Test case is failing.

- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/queues/QueueCreationTestCase.java
public jira: https://wso2.org/jira/browse/MB-908
> queue creation with : test case

- modules/integration/tests-integration/tests-amqp/src/test/resources/artifacts/mb/config/allowSharedTopicSubscriptionsConfig/broker.xml
- modules/integration/tests-integration/tests-amqp/src/test/resources/artifacts/mb/config/broker.xml
> broker.xml changes for tests (BitMap Feature)

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/MQTTClientEngine.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/MQTTConstants.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/backend/MBIntegrationBaseTest.java
- modules/integration/tests-integration/tests-mqtt/src/test/java/org/wso2/mb/integration/tests/mqtt/functional/BasicSecurityTestCase.java
- modules/integration/tests-integration/tests-mqtt/src/test/resources/testng.xml
- modules/samples/product/mqtt_IoTSample/src/main/java/org/wso2/sample/mqtt/AndesMQTTClient.java
- modules/samples/product/mqtt_IoTSample/src/main/java/org/wso2/sample/mqtt/MQTTSampleConstants.java
- modules/samples/product/mqtt_IoTSample/src/main/java/org/wso2/sample/mqtt/Main.java
- modules/samples/product/mqtt_IoTSample/src/main/java/org/wso2/sample/mqtt/model/Vehicle.java
- modules/samples/product/mqtt_chat_client/src/main/java/org/wso2/sample/mqtt/AndesMQTTClient.java
Relavent Jira ID : https://wso2.org/jira/browse/MB-722
> [MB-722] Authenticating users against Carbon user store, fixing samples and addting test cases

- pom.xml
Updated carbon commons version to 4.3.6
> Updated carbon commons version to 4.3.6

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DurableTopicServerRestartTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/testing-H2-mem.xml
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
Please refer to the following JIRA.
https://wso2.org/jira/browse/MB-941
The test class contains durable topic test cases with relation to restarting the server.
> [MB-941] Test case for receiving messages on durable topics after server restart.

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DurableTopicServerRestartTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/MultiTenantTopicTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
Fixed failing test cases related to tenant.
> Fixed failing test cases related to tenant.

- modules/integration/tests-integration/tests-amqp/src/test/resources/testing-H2-mem.xml
Commenting test case as it is failing
> Commenting test case as it is failing

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DurableTopicServerRestartTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/testing-H2-mem.xml
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
Commented H2 In-Memory test case as it is suppose to fail.
> Commented H2 In-Memory test case as it is suppose to fail.

- modules/distribution/src/main/conf/master-datasources.xml
add correct validation query for oracle.
jira - https://wso2.org/jira/browse/MB-980
> [MB-980] add correct oracle validation query to master-datasources.xml

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DurableTopicSubscriptionTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
Removing DurableTopicServerRestartTestCase test until the scenario is fixed.
> Removing DurableTopicServerRestartTestCase test until the scenario is fixed.

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesClient.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesJMSConsumer.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/load/MultiThreadedMultipleQueueTopicTestCase.java
Fixed JavaDocs and refactored the andes client used in testing.
> Andes Client Refactoring.

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/MultipleQueueSendReceiveTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
Tracked with jira : https://wso2.org/jira/browse/MB-946
> Disabling test case until resolution

- modules/integration/tests-common/admin-clients/pom.xml
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/clients/AndesAdminClient.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/utils/AndesClientConstants.java
- modules/integration/tests-integration/tests-amqp/pom.xml
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/TenantDeadLetterChannelTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/automation.xml
- modules/integration/tests-integration/tests-amqp/src/test/resources/testing-H2-mem.xml
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
- pom.xml
this pr contains test case for following jira
jira - https://wso2.org/jira/browse/MB-746
> [MB-746] add test case for tenant/super tenant dlc queue path

- modules/distribution/src/main/assembly/bin.xml
- modules/distribution/src/main/conf/axis2.xml
Added hazelcast custom serializers in axi2.xml by default.
jira - https://wso2.org/jira/browse/MB-994
> [MB-994] Added hazelcast custom serializers in axi2.xml by default

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesClient.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DurableTopicServerRestartTestCase.java
Added constant for waiting time in DurableTopicServerRestartTestCase test case.
> Code refactoring and fixes.

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesClient.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesJMSPublisher.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/configurations/AndesJMSClientConfiguration.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/configurations/AndesJMSConsumerClientConfiguration.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/configurations/AndesJMSPublisherClientConfiguration.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/utils/AndesClientUtils.java
The PR consists of the following changes : 
1. Removed unnecessary error logging as the exception are thrown to the client who is using.
2. Added a function to write messages sent by publisher to a file.
3. Fixed incorrect XML configuration reading for publisher and consumer.
4. Added JavaDocs.
> Fixed issues in andes client for xml reading and removed unnecessary logging.

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DurableTopicTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/testing-H2-mem.xml
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
Uncommenting working test cases.
> [MB-946] - Uncommented working test cases in test suits

- modules/integration/tests-integration/tests-amqp/src/test/resources/testing-H2-mem.xml
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
> Enabling selectors test case.

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/TenantDeadLetterChannelTestCase.java
This PR will fix following jira issue[1].
[1] - https://wso2.org/jira/browse/MB-1001
> [MB-1001] Purge existing dlc queue messages while running tenant dlc test

- modules/integration/tests-integration/tests-amqp/src/test/resources/testing-H2-mem.xml
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
> Commented test cases.

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesClient.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/utils/AndesClientOutputParser.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/JMSSubscriberTransactionMessageReceiveOrderTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/testing-H2-mem.xml
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
this pr will add a test case to check transacted rollback message redeliver order under amqp test suite.
jira - https://wso2.org/jira/browse/MB-1002
> [MB-1002] Added test case to check transacted rollback message redeliver order

- modules/distribution/src/main/conf/master-datasources.xml
Adding some missing data source configuration params ( for MSSQL)
> Adding datasource config params

- modules/integration/tests-integration/tests-amqp/src/test/resources/testing-H2-mem.xml
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
Commented test cases till build fix.
> Commented test cases till build fix.

- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/dlc/DLCQueueTestCase.java
- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
This pr will fix dlc ui test issues.
jira - https://wso2.org/jira/browse/MB-813
> [MB-813] Fix issues in dlc ui test case.

- modules/distribution/pom.xml
- modules/features/pom.xml
- modules/features/product/pom.xml
- modules/integration/pom.xml
- modules/integration/tests-integration/pom.xml
- modules/integration/tests-integration/reports/pom.xml
- modules/integration/tests-integration/tests-amqp/pom.xml
- modules/integration/tests-integration/tests-mqtt/pom.xml
- modules/integration/tests-platform/pom.xml
- modules/org.wso2.stratos.mb.dashboard.ui/pom.xml
- modules/org.wso2.stratos.mb.login.ui/pom.xml
- modules/p2-profile/pom.xml
- modules/styles/pom.xml
- modules/styles/product/pom.xml
- modules/styles/service/pom.xml
- pom.xml
> pom.xml changes

- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/topic/TopicCreationTestCase.java
this pr will fix following jira.
https://wso2.org/jira/browse/MB-1016
> [MB-1016] Fix issue in TopicCreationTestCase

- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/backend/MBIntegrationUiBaseTest.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/DLCContentPage.java
- modules/integration/tests-common/integration-tests-utils/src/main/resources/mapper.properties
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/dlc/DLCDurableTopicTestCase.java
- modules/integration/tests-ui-integration/src/test/resources/artifacts/mb/config/dlcConfig/broker.xml
- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
This pr will add test case for durable topic messages in dlc
jira - https://wso2.org/jira/browse/MB-813
> [MB-813] Add test case for durable topic messages in dlc

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesJMSConsumer.java
- modules/integration/tests-common/platform-tests-utils/src/main/java/org/wso2/mb/platform/common/utils/MBPlatformBaseTest.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/DifferentAckModeQueueTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/DifferentMessageTypesQueueTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/DifferentRateSubscriberTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/MultipleSubscriberMultiplePublisherTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/OrderGuaranteeTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/QueueClusterTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/SubscriptionDisconnectingTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/durable/topic/DurableTopicMessageDeliveringTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/durable/topic/DurableTopicSubscriptionTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/topic/SingleSubscriberSinglePublisherTopicTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/topic/TopicClusterTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/resources/testng.xml
Several performance test cases were failing due to minor issue. These issues are fixed here. 
Fixed readability using http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/net/HostAndPort.html .
> Fixed failing performance test cases.

- modules/distribution/src/main/assembly/bin.xml
- modules/distribution/src/main/conf/hazelcast.properties
Added configurable hazelcast timeout time.
> Added hazelcast.properties file.

- modules/distribution/src/main/assembly/bin.xml
this pr will fix minor issues in following jira.
jira - https://wso2.org/jira/browse/MB-967
> [MB-997] rename mb samples according to naming standards

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesMQTTClient.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/MQTTClientConnectionConfiguration.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/mqtt/async/AndesMQTTAsyncClient.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/mqtt/blocking/AndesMQTTBlockingClient.java
This pr will add retain option to mqtt publisher test clients
https://wso2.org/jira/browse/MB-1028
> Added mqtt retain option to mqtt publisher test clients

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/MQTTClientEngine.java
MQTT blocking client message publishing was done using a ExecutorService This led to asynchronous message publishing in MQTT blocking clients.
Fixed by not using `ExceutorService` to publish and subscribe when blocking client is used.
Jira https://wso2.org/jira/browse/MB-1035
> Blocking client asynchronous publishing issue fixed

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/load/TopicLargeMessagePublishConsumeTestCase.java
Increased waiting time for 10mb messages test case in TopicLargeMessagePublishConsumeTestCase.java
> [MB-856] Increased waiting time for 10mb messages in load test case.

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesJMSPublisher.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/configurations/AndesJMSPublisherClientConfiguration.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/TransactionalPublishingTestCase.java
Test cases to test following functionality 
- enqueue messages
- commit
- rollback
- max transactional publish batch size
JIRA: https://wso2.org/jira/browse/MB-1038
> Publisher transaction related test cases added

- modules/distribution/src/main/resources/log4j.properties
Fix for https://wso2.org/jira/browse/MB-755
> Integrate log4j configurations for moquette to standard log4j.properties

- modules/integration/tests-integration/tests-mqtt/src/test/java/org/wso2/mb/integration/tests/mqtt/functional/CleanSessionTestCase.java
Fix test case failure with qos clean session related andes changes
> Fix performCleanSessionTestCase test case

- modules/integration/tests-integration/tests-mqtt/src/test/java/org/wso2/mb/integration/tests/mqtt/functional/RetainTopicTestCase.java
- modules/integration/tests-integration/tests-mqtt/src/test/resources/testng.xml
This PR contains test case for retain feature.
jira https://wso2.org/jira/browse/MB-867
> [MB-867] Add test case for mqtt retain feature

- modules/distribution/src/main/assembly/bin.xml
- modules/samples/product/MqttRetainSample/README.txt
- modules/samples/product/MqttRetainSample/build.properties
- modules/samples/product/MqttRetainSample/build.xml
- modules/samples/product/MqttRetainSample/pom.xml
- modules/samples/product/MqttRetainSample/src/main/java/org/wso2/sample/mqtt/Main.java
- modules/samples/product/MqttRetainSample/src/main/java/org/wso2/sample/mqtt/QualityOfService.java
- modules/samples/product/MqttRetainSample/src/main/java/org/wso2/sample/mqtt/SimpleMQTTCallback.java
- modules/samples/product/MqttRetainSample/src/main/resources/log4j.properties
This PR will add sample to demonstrate mqtt retain.
jira - https://wso2.org/jira/browse/MB-1051
> [MB-1051] Add sample for mqtt retain feature.

- modules/integration/tests-ui-integration/pom.xml
> Enabled UI test cases.

- modules/integration/tests-ui-integration/pom.xml
> Revert "Enabled UI test cases."

- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/messagecontent/ViewMessageContentTestCase.java
Added driver quit to ViewMessageContentTestCase class.
> Added driver quit to ViewMessageContentTestCase class.

- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/backend/ConfigurationEditor.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/backend/MBIntegrationUiBaseTest.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/MBPage.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/configure/ConfigurePage.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/configure/UserManagementPage.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/configure/AddNewTenantTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/configure/AdminWithDifferentAdminRoleName.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/configure/NewUserPermissionTest.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/configure/UserStoreManagementTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/dlc/DLCDurableTopicTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/dlc/DLCPaginationTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/dlc/DLCQueueTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/log/ViewLogsTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/login/LoginTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/messagecontent/ViewMessageContentTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/permissions/QueuePermissionTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/permissions/TopicPermissionTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/queues/BrowseQueueContentTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/queues/BrowseQueueWithUserWithDomainName.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/queues/QueueCreationTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/queues/QueueDeleteTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/queues/QueueDeleteWithSubscriber.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/topic/TopicCreationTestCase.java
- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
JIRA - https://wso2.org/jira/browse/MB-1069.
Along with the above JIRA. I have modified the MB test framework by removing throws clause which throws 'Exception' class. I have also fixed java docs.
> [MB-1069] Added test for queues with deleting with subscribers. Modified test framework by removing parent 'Exception' class throwing methods.

- modules/integration/tests-common/integration-tests-utils/src/main/resources/mapper.properties
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/dlc/DLCQueueTestCase.java
> [Build Fix] Updated xpath properties for UI test cases. Added waiting mechanism for DLC content check UI test case

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/utils/AndesClientOutputParser.java
- modules/integration/tests-integration/tests-mqtt/src/test/java/org/wso2/mb/integration/tests/mqtt/functional/RetainTopicTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/dlc/DLCDurableTopicTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/dlc/DLCQueueTestCase.java
- modules/samples/product/MqttRetainSample/src/main/java/org/wso2/sample/mqtt/Main.java
This PR will include code review changes and code improvements.
> Code review changes and code improvements.

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/TransactionalPublishingTestCase.java
> Transaction publishing test case update

- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
Jira:
https://wso2.org/jira/browse/MB-1100
> Disable failing ui test until a fix is done.

- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/HomePage.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/TopicSubscribePage.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/TopicSubscriptionsPage.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/TopicsBrowsePage.java
- modules/integration/tests-common/integration-tests-utils/src/main/resources/mapper.properties
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/topic/TopicCreationDifferentNodeIDTestCase.java
Tests cases for JIRA - https://wso2.org/jira/browse/MB-1084
> [MB-1084] Added UI test case for checking topic subscription gets created when nodeId is changed.

- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
Jira https://wso2.org/jira/browse/MB-1100
> Enabled ViewMessageContentTestCase ui test case

- modules/samples/product/MqttRetainSample/src/main/java/org/wso2/sample/mqtt/Main.java
This will remove unwanted spaces in info logs to improve readability.
> Remove unwanted spaces in info logs.

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/MQTTClientEngine.java
- modules/integration/tests-integration/tests-mqtt/src/test/java/org/wso2/mb/integration/tests/mqtt/functional/RetainTopicTestCase.java
Added test case to verify delete retain entry function.
JIRA : https://wso2.org/jira/browse/MB-1125
> Test case for delete mqtt retain topic function

- modules/integration/tests-common/admin-clients/pom.xml
- modules/integration/tests-common/integration-tests-utils/pom.xml
- pom.xml
Jira : https://wso2.org/jira/browse/MB-1130
This change will also upgrade commons-configuration lib ( to v 1.1.0)
> [MB-1130] Fix error based flow control for mssql drivers.

- modules/integration/tests-common/integration-tests-utils/src/main/resources/mapper.properties
Only merge if https://github.com/wso2/andes/pull/181 and https://github.com/wso2/carbon-business-messaging/pull/88 are merged.
> [MB-1144] Updated DLC xpaths with dlc search function

- modules/distribution/src/main/assembly/bin.xml
- modules/samples/product/TransactionalPublisher/README.txt
- modules/samples/product/TransactionalPublisher/build.xml
- modules/samples/product/TransactionalPublisher/src/main/java/org/sample/jms/MainClass.java
- modules/samples/product/TransactionalPublisher/src/main/java/org/sample/jms/QueueConsumer.java
- modules/samples/product/TransactionalPublisher/src/main/java/org/sample/jms/TransactionalQueuePublisher.java
- modules/samples/product/TransactionalPublisher/src/main/resources/log4j.properties
JIRA - https://wso2.org/jira/browse/MB-1049
> [MB-1049] Added transactional publisher sample.

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/PurgeMessagesTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
This test case checks if messages in the DLC are deleted when a queue is purged or deleted.
Merge only if  https://github.com/wso2/andes/pull/161 is merged. Or else, the test case will fail.
> Added test case for queue purging and queue deletion

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/utils/JMSClientHelper.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/InterTenantQueueTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
JIRA URL: https://wso2.org/jira/browse/MB-1083
This depends on https://github.com/wso2/carbon-business-messaging/pull/90
> Add test case for MB-1083

- modules/integration/tests-integration/tests-amqp/src/test/resources/artifacts/mb/config/allowSharedTopicSubscriptionsConfig/broker.xml
- modules/integration/tests-integration/tests-amqp/src/test/resources/artifacts/mb/config/broker.xml
- modules/integration/tests-ui-integration/src/test/resources/artifacts/mb/config/dlcConfig/broker.xml
This PR will add changes required to test broker.xml files due to MB-1159 jira fix[1].
[1] https://wso2.org/jira/browse/MB-1159
> [MB-1159] change replaced broker.xml files in test suite

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/TenantDeleteQueueTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
JIRA - https://wso2.org/jira/browse/MB-1080
> [MB-1080] Added test case for a tenant deleting a queue.

- modules/integration/tests-integration/tests-mqtt/src/test/java/org/wso2/mb/integration/tests/mqtt/load/OneMBMessageTestCase.java
- modules/integration/tests-integration/tests-mqtt/src/test/resources/sample/sample_1KB_msg.xml
- modules/integration/tests-integration/tests-mqtt/src/test/resources/testng.xml
JIRA - https://wso2.org/jira/browse/MB-1025
> [MB-1025] Added one MB load test case for MQTT

- modules/integration/tests-integration/tests-server/pom.xml
- modules/integration/tests-integration/tests-server/src/test/java/org/wso2/mb/integration/tests/server/mgt/MetricsTestCase.java
- modules/integration/tests-integration/tests-server/src/test/resources/testng.xml
- pom.xml
JIRA - https://wso2.org/jira/browse/MB-1155
> Metrics test case

- modules/distribution/src/main/conf/master-datasources.xml
Addresses the jira https://wso2.org/jira/browse/MB-1179. Please merge https://github.com/wso2/andes/pull/266 along with this for the change to take effect
> Set default auto commit status to false

- modules/distribution/pom.xml
- modules/distribution/src/main/assembly/bin.xml
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/QueueUserAuthorizationTestCase.java
- pom.xml
Addresses the jira https://wso2.org/jira/browse/MB-1182
Upgraded the carbon kernel version from 4.4.0 to 4.4.1
Please merge https://github.com/wso2/andes/pull/278 and https://github.com/wso2/carbon-business-messaging/pull/119 along with this
> Upgraded to kernel 4.4.1

- modules/integration/tests-integration/tests-server/pom.xml
- modules/integration/tests-integration/tests-server/src/test/java/org/wso2/mb/integration/tests/server/mgt/MetricsTestCase.java
- pom.xml
This PR contains review changes of previously merged PRs.
> Review changes

- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/TopicSubscriptionsPage.java
- modules/integration/tests-common/integration-tests-utils/src/main/resources/mapper.properties
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DurableTopicSubscriptionWithSameClientIdTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/durable/topic/DurableTopicSubscriptionOnlyTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/durable/topic/DurableTopicSubscriptionTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/resources/testng.xml
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/topic/SharedDurableSubscriptionTestCase.java
- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
Merge only if https://github.com/wso2/andes/pull/285 is merged.
> Added UI shared durable subscription test cases. Fixed broken cluster tests. Added new durable cluster test.

- modules/distribution/src/main/resources/wso2server.bat
- modules/distribution/src/main/resources/wso2server.sh
JIRA - https://wso2.org/jira/browse/MB-1114
> [MB-1114] Updated server startup scripts.

- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
Uncommented the test cases that were disabled due to https://wso2.org/jira/browse/MB-1205
Please merge https://github.com/wso2/andes/pull/305 along with this or else the tests will fail.
> Uncommented fixed test cases

- modules/distribution/src/main/assembly/bin.xml
JIRA - https://wso2.org/jira/browse/MB-1209
> [MB-1209] Adding missing dependency for samples.

- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/queues/QueueDeleteTestCase.java
Test case for JIRA - https://wso2.org/jira/browse/MB-1126
> [MB-1126] Added UI queue delete test case

- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/configure/AddNewTenantPage.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/configure/AddNewTenantTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/topic/TopicTenantTestCase.java
- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
Test case for JIRA - https://wso2.org/jira/browse/MB-1180
> [MB-1180] Added UI test case for pub/sub using a tenant admin

- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
Uncommented the test cases which were commented due to https://wso2.org/jira/browse/MB-1208.
Please merge https://github.com/wso2/andes/pull/307 along with this to apply the fix
> Uncommented the test cases which were commented due to jira MB-1208

- INSTALL.txt
- README.txt
- docs/xdoc/admin_guide.xml
- docs/xdoc/installation_guide.xml
- docs/xdoc/release-notes.xml
jira : https://wso2.org/jira/browse/MB-1215
> [MB-1215] Update docs to reflect latest changes.

- modules/distribution/src/main/resources/wso2server.sh
Jira: https://wso2.org/jira/browse/MB-1216
>  [MB-1216] Increasing min heap size to 2G

- pom.xml
> andes and carbon-business-messaging version change to current development version

- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
Uncommented the ViewMessageContent test case which was commented due to https://wso2.org/jira/browse/MB-1220
Please merge https://github.com/wso2/andes/pull/315 along with this to apply the fix
> [MB-1220] Enabled ViewMessageContentTestCase

- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
JIRA - https://wso2.org/jira/browse/MB-1180
> [MB-1180] Enabled mqtt tenant ui test case.

- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/TopicsBrowsePage.java
- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
Addresses the jira https://wso2.org/jira/browse/MB-1204
> [MB-1204] Fixed issue in TopicCreationDifferentNodeIDTestCase

- modules/distribution/src/main/resources/log4j.properties
- modules/integration/pom.xml
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/MQTTClientEngine.java
- modules/integration/tests-common/platform-tests-utils/src/main/java/org/wso2/mb/platform/common/utils/MBPlatformBaseTest.java
- modules/integration/tests-platform/tests-clustering/pom.xml
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/mqtt/ClusteredCleanSessionTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/mqtt/ClusteredSecurityTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/mqtt/MQTTClusterTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/mqtt/MQTTPlatformBaseTest.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/mqtt/QualityOfServiceDataProvider.java
- modules/integration/tests-platform/tests-clustering/src/test/resources/automation.xml
- modules/integration/tests-platform/tests-clustering/src/test/resources/testng.xml
jira is : https://wso2.org/jira/browse/MB-1242
this is the first cut.
the test case : org.wso2.mb.platform.tests.clustering.mqtt.ClusteredCleanSessionTestCase
is disabled at the moment.
> [MB-1242] Adding MQTT cluster tests

- modules/integration/tests-integration/reports/src/main/resources/instrumentation.txt
- modules/integration/tests-integration/tests-amqp/src/test/resources/instrumentation.txt
- modules/integration/tests-integration/tests-mqtt/src/test/resources/instrumentation.txt
- modules/integration/tests-integration/tests-server/src/test/resources/instrumentation.txt
- modules/integration/tests-platform/tests-clustering/src/test/resources/instrumentation.txt
- modules/integration/tests-ui-integration/src/test/resources/instrumentation.txt
Jira : https://wso2.org/jira/browse/MB-1248
> [MB-1248] Changing instrumentation files

- modules/distribution/pom.xml
Jira: https://wso2.org/jira/browse/MB-1251
> [MB-1251] Skip deploying product distribution to nexus

- modules/integration/tests-integration/tests-mqtt/src/test/resources/testng.xml
Retain path has been fixed for new delivery model
jira - https://wso2.org/jira/browse/MB-1259
Reverts wso2/product-mb#194
> Revert "Comment retain topic test case"

- modules/distribution/pom.xml
- modules/distribution/src/main/assembly/bin.xml
- modules/integration/tests-common/integration-tests-utils/src/main/resources/mapper.properties
- modules/p2-profile/pom.xml
- pom.xml
jira: https://wso2.org/jira/browse/MB-1250
> [MB-1250] Upgrade carbon-identity and carbon-commonos bundles

- modules/distribution/src/main/conf/event-broker.xml
- modules/integration/pom.xml
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/clients/AndesAdminClient.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/clients/TopicAdminClient.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/MultiTenantDurableTopicTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/MultiTenantTopicTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/QueueUserAuthorizationTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/TopicUserAuthorizationTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/automation.xml
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/durable/topic/DurableTopicMessageDeliveringTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/mqtt/MQTTClusterTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/topic/DifferentAckModeTopicTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/topic/DifferentMessageTypesTopicTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/topic/MultipleSubscriberMultiplePublisherTopicTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/topic/MultipleTopicTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/topic/SingleSubscriberSinglePublisherTopicTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/topic/TopicClusterTestCase.java
- modules/p2-profile/pom.xml
- pom.xml
- existing carbon-commons event ui feature removed
- permisssion related modification done to test cases
- event-broker.xml changes to work with andes event
> andes feature integration with topic ui

- modules/integration/tests-common/integration-tests-utils/pom.xml
- pom.xml
jira: https://wso2.org/jira/browse/MB-1388
> [MB-1388] Fixing the build error

- modules/integration/tests-integration/tests-amqp/src/test/resources/artifacts/mb/config/allowSharedTopicSubscriptionsConfig/broker.xml
Removing unnecessary configurations from broker.xml files in tests.
Related to: https://wso2.org/jira/browse/MB-1230
> MB-1230 Removing unnecessary configurations from broker.xml files in tests

- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/queues/QueueCreationTestCase.java
Changed the created queue name from 'test:test' to  'QueueCreationTestQueue'
> Fixed queue creation test failure

- modules/integration/tests-common/platform-tests-utils/src/main/java/org/wso2/mb/platform/common/utils/DataAccessUtil.java
- modules/integration/tests-common/platform-tests-utils/src/main/java/org/wso2/mb/platform/common/utils/RDBMSConnectionManager.java
- modules/integration/tests-platform/tests-clustering/src/test/resources/automation.xml
Retrieve cluster test database configuration from automation.xml file.
> Modify cluster tests to retrieve cluster db configs from automation.xml file

- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/QueueClusterTestCase.java
Added a 1 second delay after deleting queue to allow async delete
queue task to complete.
> Fix QueueClusterTestCase#testSingleQueueReplication test

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/MQTTConstants.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/mqtt/ClusteredCleanSessionTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/mqtt/DataProvider/QualityOfServiceDataProvider.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/mqtt/MQTTClusterTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/mqtt/RetainClusterTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/resources/testng.xml
This PR will add cluster test case for retain and refactor code with some fixes for wrong test case namings.
> [MB-1531] Cluster test case for mqtt retain

- modules/distribution/src/main/resources/log4j.properties
Updated the classes of which debug logs should be enabled for troubleshooting.
> Updated troubleshooting logs of log4j.properties

- modules/samples/product/HierarchicalTopicsSubscriber/src/org/sample/jms/Main.java
- modules/samples/product/HierarchicalTopicsSubscriber/src/org/sample/jms/SampleHierarchicalTopicsClient.java
- modules/samples/product/HierarchicalTopicsSubscriber/src/org/sample/jms/TopicPublisher.java
Addresses the issue reported at https://wso2.org/jira/browse/MB-1566
The issue was that two subscriptions are created in the same session (which is not allowed by the broker). Creating two separate sessions for the two subscriptions resolved the issue.
> Fixed issue in the sample 'HierarchicalTopicsSubscriber'

- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/queues/QueueCreationTestCase.java
Jira : https://wso2.org/jira/browse/MB-1520
> Added test case for adding queue with colon

- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/backend/MBIntegrationUiBaseTest.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/HomePage.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/QueueSubscriptionsPage.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/TopicSubscriptionsPage.java
- modules/integration/tests-common/integration-tests-utils/src/main/resources/mapper.properties
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/configure/AddNewTenantTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/configure/NewUserPermissionTest.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/configure/UserStoreManagementTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/dlc/DLCPaginationTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/log/ViewLogsTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/login/LoginTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/messagecontent/ViewMessageContentTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/permissions/QueuePermissionTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/permissions/TopicPermissionTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/queues/BrowseQueueContentTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/queues/QueueCreationTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/queues/QueueDeleteTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/queues/QueueDeleteWithSubscriber.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/subscriptions/SubscriptionDeleteTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/topic/TopicCreationTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/topic/TopicTenantTestCase.java
- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
Fixing https://wso2.org/jira/browse/MB-1588
> added UI test cases related to subscription close feature.

- modules/integration/tests-integration/tests-amqp/src/test/resources/artifacts/mb/config/allowSharedTopicSubscriptionsConfig/broker.xml
jira: https://wso2.org/jira/browse/MB-1584
> [MB-1584] Change slotRetainTimeInMemory property in broker.xml in to a meaningful name

- pom.xml
jira: https://wso2.org/jira/browse/MB-1561
> [MB-1561] Upgrade carbon metrices lib

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/mqtt/callback/CallbackHandler.java
- modules/integration/tests-integration/tests-mqtt/src/test/java/org/wso2/mb/integration/tests/mqtt/functional/WildcardTestCase.java
Test cases for the JIRA - https://wso2.org/jira/browse/MB-1606
> Add test cases for MQTT received topic from client side

- modules/samples/product/MqttChatClient/build.xml
- modules/samples/product/MqttIoTSample/build.xml
- modules/samples/product/MqttRetainSample/build.xml
- modules/samples/product/SimpleMqttClient/build.xml
JIRA - https://wso2.org/jira/browse/MB-1384
> [MB-1384] Upgrading MQTT versions of the samples.

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesMQTTClient.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/mqtt/async/AndesMQTTAsyncClient.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/mqtt/blocking/AndesMQTTBlockingClient.java
- modules/integration/tests-integration/tests-mqtt/src/test/java/org/wso2/mb/integration/tests/mqtt/functional/WildcardTestCase.java
Test case for JIRA https://wso2.org/jira/browse/MB-1618
> Add MQTT test case for multiple subscriptions with same client

- pom.xml
jira: https://wso2.org/jira/browse/MB-1620
> [MB-1620] upgrade guava library to version 19

- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/mqtt/internal/MqttTransportServiceComponent.java
- pom.xml
- product/carbon-home/conf/broker/broker.xml
- product/pom.xml
Enabling MQTT feature since Andes core depends on some MQTT related packages. (Need to remove those dependencies from core)
> Enable MQTT feature. Disable MQTT server startup

- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/DLCContentPage.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/QueuesBrowsePage.java
- modules/integration/tests-common/integration-tests-utils/src/main/resources/mapper.properties
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/dlc/DLCReRouteAllTestCase.java
- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
JIRA - https://wso2.org/jira/browse/MB-1657
> [MB-1657] Added improvement to rereoute messages of a specific destination in DLC to a queue.

- product/carbon-home/conf/broker/datasources/master-datasources.xml
jira: https://wso2.org/jira/browse/MB-1674
> [MB-1674] Adding HikariCP related configurations

- carbon-mb/components/transports/mqtt/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/HawtDBStorageService.java
Fixing an IOException while creating a hawtdb file when MB is connected to mysql (as the message store).
> Fixing minor error while creating hawtdb file

- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/config/YAMLTransportConfigurationBuilder.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/adaptors/MessagingAdaptor.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/adaptors/andes/AndesAdaptor.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/adaptors/andes/message/MqttMessageMetaData.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/adaptors/andes/message/MqttMetaDataHandler.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/adaptors/andes/utils/MqttUtils.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/adaptors/memory/MemoryConnector.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/broker/BrokerVersion.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/broker/v311/MqttBroker.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/broker/v311/commands/Disconnect.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/broker/v311/commands/PingRequest.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/broker/v311/commands/UnSubscribe.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/internal/MqttTransportServiceComponent.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/netty/protocol/decoders/SubscribeDecoder.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/netty/protocol/encoders/SubAckEncoder.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/netty/protocol/messages/SubAckMessage.java
- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/server/Broker.java
This fixes issues reported through find-bugs in the MQTT component
> Fixing issues reported by FindBugs

- carbon-mb/components/andes/pom.xml
- carbon-mb/components/andes/src/main/java/org/wso2/carbon/andes/internal/AndesDataHolder.java
- carbon-mb/components/andes/src/main/java/org/wso2/carbon/andes/internal/AndesServiceComponent.java
- carbon-mb/features/org.wso2.carbon.andes.feature/pom.xml
- pom.xml
- product/pom.xml
- carbon-hazelcast feature removed from product installation
- Hazelcast bundle added and necessary changes did in Andes component to register as OSGi service
- Relevant pom.xml files modified with hazelcast change
> Hazelcast changes in carbon-mb

- carbon-mb/components/transports/amqp/pom.xml
- carbon-mb/components/transports/amqp/src/main/java/org/wso2/carbon/andes/amqp/resource/manager/AMQPDurableTopicResourceHandler.java
- carbon-mb/components/transports/amqp/src/main/java/org/wso2/carbon/andes/amqp/resource/manager/AMQPTopicResourceHandler.java
- pom.xml
Depends on : https://github.com/wso2/carbon-business-messaging/pull/280
> Fixing transport changes for resource handlers.

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesJMSPublisher.java
Fix Null pointer exception if the file path is not set in map message cluster test cases.
> Fix cluster test failures in DifferentMessageTypesQueueTestCase.

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/utils/AndesClientConstants.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/JMSRoutingKeyPropertyTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
JIRA - https://wso2.org/jira/browse/MB-1699
> [MB-1699] Added test cases for JMS routing key property.

- modules/distribution/src/main/assembly/bin.xml
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesClient.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesJMSConsumer.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/utils/AndesClientConstants.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/utils/JMSAcknowledgeMode.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/PerMessageAcknowledgementsTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/RedeliveryDelayTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
- modules/samples/product/PerMessageAcknowledgeSample/README.txt
- modules/samples/product/PerMessageAcknowledgeSample/build.xml
- modules/samples/product/PerMessageAcknowledgeSample/src/org/sample/jms/Main.java
- modules/samples/product/PerMessageAcknowledgeSample/src/org/sample/jms/SamplePerMessageAckSubscriber.java
- modules/samples/product/PerMessageAcknowledgeSample/src/org/sample/jms/SampleQueueSenderForPerMessageAckSample.java
- modules/samples/product/RedeliveryDelaySample/README.txt
- modules/samples/product/RedeliveryDelaySample/build.xml
- modules/samples/product/RedeliveryDelaySample/src/org/sample/jms/Main.java
- modules/samples/product/RedeliveryDelaySample/src/org/sample/jms/SampleDelayedRedeliverySubscriber.java
- modules/samples/product/RedeliveryDelaySample/src/org/sample/jms/SampleQueueSenderForDelayedRedeliverySample.java
JIRA - https://wso2.org/jira/browse/MB-1687
> [MB-1687] Added test cases for per message ack and redelivery delay. Adding samples for per message ack and redelivery delay.

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/PerMessageAcknowledgementsTestCase.java
> Revert "Increased ackWaitTimeout for Per message ack test."

- modules/distribution/src/main/assembly/bin.xml
- modules/samples/product/JmsExpirationSample/README.txt
- modules/samples/product/JmsExpirationSample/build.xml
- modules/samples/product/JmsExpirationSample/src/org/sample/jms/Main.java
- modules/samples/product/JmsExpirationSample/src/org/sample/jms/SampleQueueReceiver.java
- modules/samples/product/JmsExpirationSample/src/org/sample/jms/SampleQueueSender.java
Sample for message TTL
Related JIRA link : https://wso2.org/jira/browse/MB-1686
Please merge the following along this.
1. https://github.com/wso2/andes/pull/660
2. https://github.com/wso2/carbon-business-messaging/pull/298
> [MB-1686] Adding sample for message TTL

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesClient.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesJMSConsumer.java
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/MixedQueueTopicTestCase.java
> Revert "Fix incorrect assert in cluster tests"

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/SubTopicUserAuthorizationTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
jira : https://wso2.org/jira/browse/MB-1712
> Add test case for sub topic user authorization

- modules/distribution/src/main/resources/log4j.properties
The below entry should exist at INFO log level to enable disable Message Tracer in UI.
> Fix MB-1724

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DLCMessageExpiryTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/MessageExpirationTestCase.java
- modules/integration/tests-platform/tests-clustering/src/test/resources/testng.xml
Integration tests and Cluster tests are added for message expiry
jira: https://wso2.org/jira/browse/MB-1686
> [MB-1686] Add integration and cluster test cases for message expiration

- carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/adaptors/andes/subscriptions/MqttLocalSubscription.java
> Fix naming issues with getMessageId method

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/PurgeMessagesTestCase.java
- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
Modified PurgeMessagesTestCase to get DLC queue using new admin service method.
> Modified PurgeMessagesTestCase 

- modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/MessageExpirationTestCase.java
- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
Modify the message expiration cluster test
> Modify message expiration cluster test case

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DLCMessageExpiryTestCase.java
- Messages didn't move to DLC during the time of thread sleeps in the test  case and assertion failed. Decrease AndesAckWaitTimeOut to 3 seconds in the startup of the test as a fix.
> DLCMessageExpiryTestCase failing issue fixed.

- modules/integration/tests-common/integration-tests-utils/src/main/resources/mapper.properties
- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
Fix the UI tests for new subscription UI.
Associated JIRA Link: https://wso2.org/jira/browse/MB-1746
> [MB-1746] Fix UI Tests for new UI change

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/TenantDeadLetterChannelTestCase.java
Addes test case for the issue reported at https://wso2.org/jira/browse/MB-1784
> [MB-1784] - Added test method for tenant dlc with durable subscriptions

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/MultiTenantDurableTopicTestCase.java
Modified test case according to https://wso2.org/jira/browse/MB-1783
> [MB-1783] modified relevant test methods

- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/QueueSubscriptionsPage.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/TopicSubscriptionsPage.java
- modules/integration/tests-common/integration-tests-utils/src/main/resources/mapper.properties
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DLCMessageExpiryTestCase.java
- modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/subscriptions/SubscriptionSearchTestCase.java
- modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml
- modules/samples/product/JmsExpirationSample/src/org/sample/jms/SampleQueueReceiver.java
Add UI test cases for subscription filtering
> Add Subscription Filtering UI test & Code refactor

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DLCMessageExpiryTestCase.java
Remove DLC message expiry config from test case
Associated JIRA Link : https://wso2.org/jira/browse/MB-1767
> [MB-1767] Remove DLC message expiration config from test case

- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/DLCContentPage.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/QueuesBrowsePage.java
- modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/TopicsBrowsePage.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/QueueTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/QueueUserAuthorizationTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/TopicUserAuthorizationTestCase.java
Added/modified test cases according to the case sentsitiviti introduced by https://github.com/wso2/andes/pull/831
> Modified test methods according to case sensitive queue names and added case sensitive test case

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/dtx/DtxStartPositiveTestCase.java
Added an assertion for the browse queue operation before subscribing to 'DtxStartPositiveTestCaseXaStartJoinQueuePublishTestCase' inorder to identify the path (publishing/delivery) of the issue. 
The issue is tracked at https://wso2.org/jira/projects/MB/issues/MB-1910
> [MB-1910] added browse queue to debug failing xaStartJoinQueuePublishTestCase

- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesJMSConsumer.java
- modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/configurations/AndesJMSConsumerClientConfiguration.java
- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/AMQPSessionRecoverTestCase.java
- modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml
This PR depends with PR: https://github.com/wso2/andes/pull/840
Added necessary test cases for session.recover()
> [MB-1887] Added test cases for amq session recover.

- modules/distribution/src/main/resources/log4j.properties
>> Reorganized file
>> Added renamed classes
> Reorganised log4j.properties file.

- modules/tools/migration/src/main/java/org/wso2/mb/migration/DBConnector.java
Update migration tool to convert binding keys in
MB_BINDING table into all simple format.
Resolves : https://wso2.org/jira/browse/MB-1883
> [MB-1883] Update migration tool to convert binding keys in MB_BINDING table

- modules/tools/migration/pom.xml
- modules/tools/migration/src/main/java/org/wso2/mb/migration/DBConnector.java
- modules/tools/migration/src/main/java/org/wso2/mb/migration/Main.java
- modules/tools/migration/src/main/java/org/wso2/mb/migration/MigrationException.java
- modules/tools/migration/src/main/java/org/wso2/mb/migration/Modifier.java
- modules/tools/migration/src/main/java/org/wso2/mb/migration/Processor.java
- modules/tools/migration/src/main/resources/log4j.properties
Update migration tool to close resources upon
closing the database connection to avoid number of
open cursors in oracle db exceeding  maximum
allowed limit
Resolves : https://wso2.org/jira/browse/MB-1933
> [MB-1933] Update migration tool to close resources upon closing the database connection

- modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/QueueMessageExpireTestCase.java
Change "performManyQueueExpirySendReceiveTestCase" assertion logic to be more reliable. Wait until required number of messages received by consumers before exit waiting. Added a timeout to continue tests if required number of messages didn't receive after a time limit.
> Change performManyQueueExpirySendReceiveTestCase assertion logic

- pom.xml
- product/pom.xml
- product/src/assembly/bin.xml
> Fix deployment folder creation issue due to updates carbon-deployment feature
