modules/distribution/pom.xml
modules/features/service/org.wso2.stratos.mb.dashboard.ui.feature/pom.xml
modules/features/service/org.wso2.stratos.mb.deployment.feature/pom.xml
modules/features/service/org.wso2.stratos.mb.login.ui.feature/pom.xml
modules/features/service/org.wso2.stratos.mb.styles.feature/pom.xml
modules/features/service/pom.xml
modules/integration/pom.xml
modules/integration/tests-common/admin-clients/pom.xml
modules/org.wso2.stratos.mb.dashboard.ui/pom.xml
modules/org.wso2.stratos.mb.login.ui/pom.xml
modules/samples/product/mqtt_IoTSample/pom.xml
modules/samples/product/mqtt_chat_client/pom.xml
modules/samples/product/simple_mqtt_client/pom.xml
pom.xml

Eclipse paho mqtt-client version downgraded to 0.4.0. Removed unnecessary dependencies. Added versions for sample modules.

Eclipse paho mqtt-client version downgraded to 0.4.0

---

modules/distribution/pom.xml
modules/integration/pom.xml
modules/integration/tests-common/admin-clients/pom.xml
modules/integration/tests-platform/tests-clustering/pom.xml
pom.xml

Fixed the following errors that occurs when running test cases.
1. Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.tenant.mgt.message.TenantDeleteClusterMessage
2. Caused by: java.lang.ClassNotFoundException: org.wso2.andes.jndi.PropertiesFileInitialContextFactory

Fixed missing 'TenantDeleteClusterMessage' class and missing 'PropertiesFileInitialContextFactory' class

---

modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DurableTopicSubscriptionWithSameClientIdTestCase.java

add restore configuration method to durable topic with same subscription Id Test Case. This will restore broker.xml to original state.

add restore configuration method to durable topic with same subscription Id test case

---

modules/distribution/src/main/conf/master-datasources.xml
modules/integration/tests-integration/tests-amqp/src/test/resources/testing-H2-mem.xml

Removing DurableTopicSubscriptionWithSameClientIdTestCase from H2 in-mem tests and adding ;DB_CLOSE_DELAY=-1 to in-mem mode in master-datasources.xml.

Adding ;DB_CLOSE_DELAY=-1 to in-mem mode in master-datasources.xml

---

modules/distribution/src/main/conf/hazelcast.properties

- hazelcast.shutdownhook.enabled=false property added to hazelcast.property file to fix  Hazelcast instance is not active exception when MB server gracefully shutting down.

MB-1021 issue fixed

---

modules/distribution/src/main/conf/master-datasources.xml

By default we don't need to have the in-memory mode. Hence commenting it out

In-memory mode related datasource commented out

---

modules/distribution/src/main/conf/master-datasources.xml

In-memory mode needs to be enabled to run in memory mode tests
Until we find a proper way to activate this, within the framework (need to change broker.xml + master-datasources.xml) when we restart server for in-memory tests, uncommenting.

Memory mode needs to be enabled to run in-memory tests

---

modules/distribution/src/main/conf/master-datasources.xml

These configurations are required to reconnect to Cassandra cluster during a a disconnect.
Jira: https://wso2.org/jira/browse/MB-1043

MB-1043 adding configurations related to reconnecting cassandra

---

modules/distribution/src/main/conf/cipher-text.properties
modules/distribution/src/main/conf/cipher-tool.properties

This is with reference to jiras :
https://wso2.org/jira/browse/MB-924 
https://wso2.org/jira/browse/MB-1160
Default ciphertool entries have been added for AMQP / MQTT SSL keystore passwords.
This is dependent on : 
https://github.com/wso2/andes/pull/219
https://github.com/wso2/carbon-business-messaging/pull/100

Adding amqp/mqtt ssl passwords to cipher tool configs

---

modules/distribution/src/main/conf/master-datasources.xml

Removed autoCommit=false from CarbonDB configurations in master-datasources.xml

Removed autocommit false from CarbonDB

---

modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/DLCContentPage.java

Tests fail with a no such element method thrown when trying to clear the DLC when the dlc is empty.
This was corrected by checking whether the dlc message table row count is greater than 1

Fixed exception thrown when clearing empty DLC in build tests

---

modules/distribution/src/main/assembly/bin.xml

Addresses the jira https://wso2.org/jira/browse/MB-1175. Added the securevault jar to client-lib
Please merge https://github.com/wso2/andes/pull/253 and https://github.com/wso2/andes/pull/260 along with this to enable securevault support

[WIP] Added securevault jar to client-lib

---

modules/integration/tests-common/integration-tests-utils/src/main/java/org/wso2/mb/integration/common/utils/ui/pages/main/DLCContentPage.java
modules/integration/tests-common/integration-tests-utils/src/main/resources/mapper.properties
modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/dlc/DLCQueueTestCase.java
modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml

Enabled the DLCDurableTopicTestCase which was disabled due to https://wso2.org/jira/browse/MB-1184.
Also, corrected an error in deleteAllDLCMessages() method in DLCContentPage which was caused by the fact that messages were counted from a wrong table.
Please merge https://github.com/wso2/andes/pull/281 along with this or else the test will fail.

Fixed durable topic messages not being restored from DLC issue

---

modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/PurgeMessagesTestCase.java

Addresses the jira issue at https://wso2.org/jira/browse/MB-1187
The existence of the queue was tested right after deleting the queue and by that time, the queue was not actually deleted from the back-end. This was solved by adding a thread sleep of 1 sec.

Refactored purgeMessagesTestCase

---

modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/dlc/DLCQueueTestCase.java
modules/integration/tests-ui-integration/src/test/resources/testng-server-mgt.xml

Addresses the jira https://wso2.org/jira/browse/MB-1218
DLCQueueTestCase was written in such a was that rather that the restoring functionality was tested by matching the id of the first message in the content table against the restored message id. It was modified to check the existence of the message id in the content table by this PR.

Modified DLCQueue Test Case

---

modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesJMSConsumer.java
modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/utils/AndesClientOutputParser.java
modules/integration/tests-common/platform-tests-utils/src/main/java/org/wso2/mb/platform/common/utils/DataAccessUtil.java
modules/integration/tests-common/platform-tests-utils/src/main/java/org/wso2/mb/platform/common/utils/RDBMSConnectionManager.java
modules/integration/tests-common/platform-tests-utils/src/main/java/org/wso2/mb/platform/common/utils/RDBMSConstants.java
modules/integration/tests-common/platform-tests-utils/src/main/java/org/wso2/mb/platform/common/utils/exceptions/DataAccessUtilException.java
modules/integration/tests-platform/tests-clustering/pom.xml
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/DifferentAckModeQueueTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/DifferentMessageTypesQueueTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/DifferentRateSubscriberTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/MultipleSubscriberMultiplePublisherTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/OrderGuaranteeTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/QueueAckMixTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/QueueClusterTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/SubscriptionDisconnectingTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/durable/topic/DurableTopicMessageDeliveringTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/durable/topic/DurableTopicSubscriptionTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/topic/DifferentAckModeTopicTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/topic/DifferentMessageTypesTopicTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/topic/MultipleTopicTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/topic/SingleSubscriberSinglePublisherTopicTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/topic/TopicClusterTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/resources/testng.xml
pom.xml

JIRA - https://wso2.org/jira/browse/MB-1197
This PR contains modified cluster test cases with automated database assertion and message count configuration feature.
* Automate Database Assertion
At the end of each test case, database will be validated for any undelivered/left messages or invalid slots.
Before running cluster tests, we need to configure JDBC URL, Database username and password in product-mb/modules/integration/tests-common/platform-tests-utils/src/main/java/org/wso2/mb/platform/common/utils/RDBMSConnectionManager.java
* Message Count Configuration
This feature allows configuring global parameter which will be used by test cases to send/receive configured number of messages.
Message count can be configured using <parameter name="messageCount" value="1000" /> in …

[MB-1197] Automated database assertion and message count configuration

---

modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/clients/AndesAdminClient.java

Addresses the changes made to the core by wso2/andes#386 due to https://wso2.org/jira/browse/MB-1268
Please merge https://github.com/wso2/andes/pull/386 and https://github.com/wso2/carbon-business-messaging/pull/171 along with this.

[MB-1268] Implemented message count retrieval for all queues

---

modules/p2-profile/pom.xml
pom.xml

Upgraded multitenancy, registry and commons versions.
multitenancy-4.4.4 requires registry-4.5.0 and commons-4.4.8.

multitenancy-4.4.4, registry-4.5.0 and commons-4.4.8 upgrade

---

modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/LZ4CompressionTestCase.java

this PR will add two test cases for message content compression for topic and durable topic.
dependencies : https://github.com/wso2/andes/pull/597

[MB-1667] add compression test cases for topics and durable topics

---

carbon-mb/components/transports/mqtt/pom.xml
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/config/MqttTransportConfiguration.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/config/MqttWebsocketTransportProperties.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/etc/conf/mqtt-transports.yaml
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/MqttWebSocketServer.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/adaptors/andes/AndesAdaptor.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/adaptors/andes/AndesPublisherAcknowledgementProcessor.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/adaptors/andes/message/MqttMessageContext.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/adaptors/andes/subscriptions/MqttLocalSubscription.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/adaptors/memory/MemoryConnector.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/broker/BrokerVersion.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/broker/Command.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/broker/MqttChannel.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/broker/PublisherAcknowledgementProcessor.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/broker/v311/MqttBroker.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/broker/v311/commands/Connect.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/broker/v311/commands/Disconnect.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/internal/MqttTransportServiceComponent.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/mqtt/netty/handlers/MqttMessagingHandler.java
carbon-mb/components/transports/mqtt/src/main/java/org/wso2/carbon/andes/transports/server/Broker.java
carbon-mb/components/transports/mqtt/src/test/java/org/wso2/carbon/transport/tests/mqtt/broker/v311/MqttBrokerTest.java
carbon-mb/components/transports/mqtt/src/test/java/org/wso2/carbon/transport/tests/mqtt/broker/v311/adaptors/MockMemoryAdaptor.java
carbon-mb/components/transports/mqtt/src/test/java/org/wso2/carbon/transport/tests/mqtt/broker/v311/client/ClientMessageReceiver.java
carbon-mb/components/transports/mqtt/src/test/java/org/wso2/carbon/transport/tests/mqtt/broker/v311/dataprovider/MqttBrokerDataProvider.java
carbon-mb/components/transports/mqtt/src/test/java/org/wso2/carbon/transport/tests/mqtt/broker/v311/dataprovider/commands/Message.java
carbon-mb/components/transports/mqtt/src/test/resources/testng.xml
product/carbon-home/conf/transports/mqtt-transports.yaml

This would allow communicating MQTT messages via websockets. The transport could further be verified for its interoperability through the online websocket client [1]
[1] http://www.hivemq.com/demos/websocket-client/

Introducing MQTT over Websocket transport and adding unit tests

---

modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesClient.java
modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/AndesJMSConsumer.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/MixedQueueTopicTestCase.java

AtomicLong value returned by AndesJMSConsumer is checked against a long value leading to a
Object assert.
Fixed by returning a long value instead of AtomicLong

Fix incorrect assert in cluster tests

---

modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/utils/AndesClientConstants.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/DifferentRateSubscriberTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/MixedQueueTopicTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/MultipleSubscriberMultiplePublisherTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/OrderGuaranteeTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/QueueClusterTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/SubscriptionDisconnectingTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/durable/topic/DurableTopicSubscriptionTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/mqtt/ClusteredSecurityTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/mqtt/MQTTClusterTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/topic/SingleSubscriberSinglePublisherTopicTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/topic/TopicClusterTestCase.java

Provides changes required for the change in https://github.com/wso2/andes/pull/671
Added a thread sleep for cluster tests which use different nodes for message publishing and subscribing so that cluster events are synced in RDBMS mode.

Changed thread sleep for cluster tests to work with RDBMS cluster notification synchronization

---

modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DLCMessageExpiryTestCase.java

For DLC Message expiry test case, the maximum redelivery attempt is set to 1 (default value is 10). So after this test case, there is a need to reset to the default value. 
JIRA Link : https://wso2.org/jira/browse/MB-1744

[MB-1744] Reset configurations after DLCMessageExpiryTestCase

---

modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/dtx/DtxRollbackPositiveTestCase.java

Change performClientQueueAcknowledgeTestCase to use the same consumer to receive messages after rollback

Change performClientQueueAcknowledgeTestCase 

---

modules/integration/tests-common/admin-clients/src/main/java/org/wso2/mb/integration/common/clients/operations/utils/AndesClientConstants.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/LZ4CompressCompatibilityTestCase.java
modules/integration/tests-platform/tests-clustering/src/test/java/org/wso2/mb/platform/tests/clustering/mqtt/LZ4CompressCompatibilityMQTTClusterTestCase.java

Added a thread sleep for cluster tests which use different nodes for message publishing and subscribing so that cluster events are synced in RDBMS mode. Same was done prviously for other test cases in https://github.com/wso2/product-mb/pull/419

Added thread sleep for cluster tests

---

modules/integration/tests-ui-integration/src/test/java/org/wso2/carbon/mb/ui/test/subscriptions/SubscriptionSearchTestCase.java

The reason was the fix of #422, we have removed appending subscriber queue name into the identifier in the subscription page.

subscription search by ID could not assert in the test case

---

modules/distribution/src/main/conf/axis2.xml

Removed serializers used in hazelcast slot agent. 
Related to https://github.com/wso2/andes/pull/852 and https://github.com/wso2/carbon-business-messaging/pull/426
The issue is tracked in at https://wso2.org/jira/browse/MB-1915

Removed serializers for Hazelcast based slot implementation

---

modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/DurableTopicMessageExpiryTestCase.java
modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/QueueMessageExpireTestCase.java
modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/TopicMessageExpiryTestCase.java
modules/integration/tests-integration/tests-amqp/src/test/resources/testng.xml

Fixed QueueMessageExpireTestCase to assert only the summation of number of messages received by two queue consumers.

Renamed tests for message expiration

---

modules/distribution/src/main/assembly/bin.xml
modules/p2-profile/pom.xml

These tools are not used in WSO2 MB. Hence Removed.

Removed wsdl based tools from MB.

---

modules/integration/tests-integration/tests-amqp/src/test/java/org/wso2/mb/integration/tests/amqp/functional/AMQPSessionRecoverTestCase.java

AMQPSessionRecoverTestCase consists of the test methods, performSessionRecoverWithoutAckTestCase, performSessionRecoverWithAckTestCase and performSessionRecoverAndDLCTestCase which use the same queue 'recoverTestQueue' that is purged at the end of each test method.
This could result in rest of the test methods being failed in the case of a failure of a single method, since the queue will not be purged. 
This PR seperates the queue names so that the test methods are made independent.

[MB-1927] seperate queue names for recover test methods
